namespace RansomGuard.Agent.Core.Persistence.Entities;

/// <summary>
/// Alert generated by the EXFIL WATCH module for suspected data exfiltration.
/// </summary>
public sealed class ExfilAlert
{
    /// <summary>Unique alert identifier.</summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>Detection rule that triggered the alert.</summary>
    public required string RuleName { get; init; }

    /// <summary>Severity: Low, Medium, High, Critical.</summary>
    public required string Severity { get; init; }

    /// <summary>Process ID of the suspect process.</summary>
    public required int ProcessId { get; init; }

    /// <summary>Process name at time of detection.</summary>
    public required string ProcessName { get; init; }

    /// <summary>Destination address or domain.</summary>
    public required string Destination { get; init; }

    /// <summary>Destination port.</summary>
    public int? DestinationPort { get; init; }

    /// <summary>Total bytes transferred in the detection window.</summary>
    public required long BytesTransferred { get; init; }

    /// <summary>Human-readable description of the finding.</summary>
    public required string Description { get; init; }

    /// <summary>Action taken (Alert, Block, Throttle).</summary>
    public required string ActionTaken { get; init; }

    /// <summary>UTC timestamp when the alert was generated.</summary>
    public DateTime DetectedAt { get; init; } = DateTime.UtcNow;

    /// <summary>Cross-link to GenealogyRecord for process attribution.</summary>
    public Guid? GenealogyId { get; init; }
}
