/**
 * Style Dictionary build pipeline — ADR-FE-007
 *
 * Transforms the 3-tier token JSON (reference -> system -> component) into:
 * 1. CSS custom properties (consumed by Tailwind via tailwind.config.ts)
 * 2. TypeScript declarations (for type-safe token references in components)
 *
 * Run via: npm run tokens:build
 *
 * Source files (in load order — order matters for {ref.x} / {sys.x} resolution):
 *   - reference.json   (Tier 1 — primitives)
 *   - system.json      (Tier 2 — semantic, references Tier 1)
 *   - component.json   (Tier 3 — component, references Tier 2)
 */

const StyleDictionary = require('style-dictionary');

// Custom format: CSS variables with kebab-case names, preserving the
// reference chain as CSS var() references (outputReferences) so that
// changing a Tier-1 value cascades without rebuilding consumers.
StyleDictionary.registerFormat({
  name: 'css/rgcm-variables',
  formatter: function ({ dictionary, options }) {
    const { outputReferences } = options;
    const header = `/**\n * DO NOT EDIT DIRECTLY\n * Generated by Style Dictionary from design-tokens/*.json\n * Run \`npm run tokens:build\` to regenerate.\n */\n`;
    const vars = dictionary.allProperties
      .map((prop) => {
        const value = outputReferences && prop.original.value && typeof prop.original.value === 'string' && prop.original.value.startsWith('{')
          ? dictionary.usesReference(prop.original.value)
            ? `var(--${dictionary.getReferences(prop.original.value)[0]?.name ?? prop.name})`
            : prop.value
          : prop.value;
        return `  --${prop.name}: ${value};`;
      })
      .join('\n');
    return `${header}:root {\n${vars}\n}\n`;
  },
});

module.exports = {
  source: ['design-tokens/reference.json', 'design-tokens/system.json', 'design-tokens/component.json'],

  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/rgcm-variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },

    ts: {
      transformGroup: 'js',
      buildPath: 'src/types/',
      files: [
        {
          destination: 'design-tokens.ts',
          format: 'typescript/es6-declarations',
          options: {
            outputStringLiterals: true,
          },
        },
      ],
    },
  },
};
