#!/usr/bin/env bash
#
# RansomGuard-CM GRID — one-time server bootstrap.
#
# Creates the persistent state that must survive every redeployment:
#   /opt/ransomguard/shared/.env    generated secrets (never in git, never in CI)
#   /opt/ransomguard/shared/pki     internal CA + server cert + Ed25519 keys
#   /opt/ransomguard/shared/tls     browser-facing certificate for the dashboard
#
# Safe to re-run: every step is skipped when its output already exists.
#
# Usage (on the server):
#   ./bootstrap.sh <hospital_name> <country_code>
#
set -euo pipefail

HOSPITAL_NAME="${1:-Hopital Central Yaounde}"
COUNTRY_CODE="${2:-CM}"

SHARED_DIR="${GRID_SHARED_DIR:-/opt/ransomguard/shared}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== GRID bootstrap ==="
echo "Shared state : $SHARED_DIR"

mkdir -p "$SHARED_DIR"/{pki,tls,dashboard-dist,agent-packages}
chmod 700 "$SHARED_DIR/pki"

# ── Tailscale identity ────────────────────────────────────────────
TS_IP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
# jq is the reliable reader here: `tailscale status --json` is pretty-printed,
# so a naive "DNSName":" grep silently returns nothing.
TS_DNS="$(tailscale status --json 2>/dev/null | jq -r '.Self.DNSName // empty' | sed 's/\.$//' || true)"
if [ -z "$TS_IP" ]; then
    echo "[FAIL] Tailscale is not up on this host -- the GRID server is only reachable over the tailnet." >&2
    exit 1
fi
echo "Tailscale IP : $TS_IP"
echo "MagicDNS     : ${TS_DNS:-<none>}"

# Allow the deploy user to drive tailscale (needed by refresh-tls.sh in CI,
# which has no TTY to answer a sudo password prompt).
sudo -n tailscale set --operator="$(id -un)" 2>/dev/null     || sudo tailscale set --operator="$(id -un)" 2>/dev/null     || echo "[warn] could not set tailscale operator -- certificate renewal will need sudo"

# ── 1. Internal PKI (agent mTLS) ──────────────────────────────────
EXTRA_SANS="IP:${TS_IP}"
[ -n "$TS_DNS" ] && EXTRA_SANS="DNS:${TS_DNS},${EXTRA_SANS}"

if [ -f "$SHARED_DIR/pki/server.key" ]; then
    echo "[skip] PKI already initialised"
else
    echo "[1/4] Generating internal PKI (SANs: $EXTRA_SANS)"
    cp "$SCRIPT_DIR/pki/init-pki.sh" "$SHARED_DIR/pki/init-pki.sh"
    chmod +x "$SHARED_DIR/pki/init-pki.sh"
    "$SHARED_DIR/pki/init-pki.sh" "$HOSPITAL_NAME" "$COUNTRY_CODE" "$EXTRA_SANS"
fi

# ── 2. Secrets ────────────────────────────────────────────────────
if [ -f "$SHARED_DIR/.env" ]; then
    echo "[skip] .env already exists -- secrets left untouched"
else
    echo "[2/4] Generating .env with fresh secrets"
    rnd() { openssl rand -base64 "$1" | tr -d '\n=+/' | cut -c1-"$2"; }
    cat > "$SHARED_DIR/.env" <<ENVEOF
# Generated by bootstrap.sh on $(date -Is) -- DO NOT COMMIT
MYSQL_ROOT_PASSWORD=$(rnd 48 32)
MYSQL_DATABASE=ransomguard_grid
MYSQL_USER=grid
MYSQL_PASSWORD=$(rnd 48 32)
REDIS_PASSWORD=$(rnd 48 32)
GRID_JWT_SECRET_KEY=$(rnd 96 64)
GRID_ENVIRONMENT=production
GRID_LOG_LEVEL=INFO
GRID_ALIENVAULT_OTX_API_KEY=

# Published on the Tailscale interface only -- Docker bypasses UFW
BIND_ADDR=${TS_IP}
NGINX_HTTPS_PORT=443
NGINX_DASHBOARD_PORT=8443
NGINX_HTTP_PORT=80

# Host paths for assets that are deployed, not built into the image
TLS_PUBLIC_DIR=${SHARED_DIR}/tls
DASHBOARD_DIST_DIR=${SHARED_DIR}/dashboard-dist
AGENT_PACKAGES_DIR=${SHARED_DIR}/agent-packages

# Public hostname used by agents and by the dashboard one-liner
GRID_PUBLIC_HOST=${TS_DNS:-$TS_IP}
GRID_TAILSCALE_IP=${TS_IP}

# Email notifications (Sprint 8) -- fill in to enable
GRID_SMTP_ENABLED=false
GRID_SMTP_HOST=in-v3.mailjet.com
GRID_SMTP_PORT=587
GRID_SMTP_USERNAME=
GRID_SMTP_PASSWORD=
GRID_SMTP_FROM_EMAIL=noreply@ransomguard.local
GRID_SMTP_FROM_NAME="RansomGuard-CM"
GRID_AGENT_DISCONNECT_TIMEOUT_MINUTES=5

# First administrator -- consumed by scripts/seed_initial_data.py
GRID_SEED_TENANT_NAME="${HOSPITAL_NAME}"
GRID_SEED_TENANT_CODE=default
GRID_SEED_ADMIN_EMAIL=admin@ransomguard.local
GRID_SEED_ADMIN_NAME="Administrateur"
GRID_SEED_ADMIN_PASSWORD=$(rnd 32 20)!Aa1

# One account per remaining role, so the RBAC matrix can be exercised on a
# fresh installation. Delete these three lines to skip creating them.
GRID_SEED_ANALYST_EMAIL=analyste@ransomguard.local
GRID_SEED_ANALYST_PASSWORD=$(rnd 32 20)!Aa1
GRID_SEED_AUDITOR_EMAIL=auditeur@ransomguard.local
GRID_SEED_AUDITOR_PASSWORD=$(rnd 32 20)!Aa1
ENVEOF
    chmod 600 "$SHARED_DIR/.env"
    echo "[ok] .env written (chmod 600)"
fi

# ── 3. Browser-facing certificate ─────────────────────────────────
echo "[3/4] Dashboard certificate"
"$SCRIPT_DIR/refresh-tls.sh" || echo "[warn] TLS refresh reported a problem -- see above"

# ── 4. Scheduled maintenance ──────────────────────────────────────
echo "[4/4] Installing systemd timers (TLS renewal, nightly backup)"
if sudo -n true 2>/dev/null || sudo true; then
    sudo cp "$SCRIPT_DIR"/systemd/ransomguard-*.{service,timer} /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable --now ransomguard-tls-renew.timer ransomguard-backup.timer
    systemctl list-timers --no-pager 'ransomguard-*' | head -4
else
    echo "[warn] no sudo -- timers not installed"
fi

echo ""
echo "=== Bootstrap complete ==="
echo "Admin credentials:"
grep -E '^GRID_SEED_ADMIN_(EMAIL|PASSWORD)=|^GRID_SEED_TENANT_CODE=' "$SHARED_DIR/.env"
echo ""
echo "Back up offline: $SHARED_DIR/pki/ca.key, intermediate.key, threat-intel-ed25519.key"
