// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RansomGuard.Agent.Core.Persistence;

#nullable disable

namespace RansomGuard.Agent.Core.Persistence.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    [Migration("20260523020100_AddNetworkBaseline")]
    partial class AddNetworkBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");
#pragma warning restore 612, 618
        }
    }
}
