"""add ed25519_public_key_pem to agent_certificate

Revision ID: 0fdc10883121
Revises: 28c095d60e26
Create Date: 2026-05-29 03:54:37.203500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdc10883121'
down_revision: Union[str, Sequence[str], None] = '28c095d60e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_certificates', sa.Column('ed25519_public_key_pem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_certificates', 'ed25519_public_key_pem')
    # ### end Alembic commands ###
