"""initial schema sprint 6 21 tables

Revision ID: 28c095d60e26
Revises: 
Create Date: 2026-05-29 03:00:02.459461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '28c095d60e26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('code', name=op.f('uq_tenants_code'))
    )
    op.create_table('threat_intel_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_string', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('package_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('ed25519_signature', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Published', 'Deprecated', name='threatintelstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_intel_versions')),
    sa.UniqueConstraint('version_string', name=op.f('uq_threat_intel_versions_version_string'))
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('hardware_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('provisioned', 'active', 'disconnected', 'decommissioned', name='agentstatus'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agents_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.Enum('Debug', 'Info', 'Warning', 'Error', 'Critical', name='loglevel'), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_system_logs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index(op.f('ix_system_logs_tenant_id'), 'system_logs', ['tenant_id'], unique=False)
    op.create_table('threat_intel_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['threat_intel_versions.id'], name=op.f('fk_threat_intel_packages_version_id_threat_intel_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_intel_packages'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('agent_certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_certificates_agent_id_agents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_certificates')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_agent_certificates_serial_number'))
    )
    op.create_table('agent_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_configurations_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], name=op.f('fk_agent_configurations_applied_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_configurations_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_configurations'))
    )
    op.create_index(op.f('ix_agent_configurations_tenant_id'), 'agent_configurations', ['tenant_id'], unique=False)
    op.create_table('agent_heartbeats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('threat_intel_version', sa.String(length=50), nullable=True),
    sa.Column('modules_status_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_heartbeats_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_heartbeats_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_heartbeats'))
    )
    op.create_index(op.f('ix_agent_heartbeats_tenant_id'), 'agent_heartbeats', ['tenant_id'], unique=False)
    op.create_table('agent_threat_intel_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_threat_intel_versions_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_agent_threat_intel_versions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['threat_intel_versions.id'], name=op.f('fk_agent_threat_intel_versions_version_id_threat_intel_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_threat_intel_versions'))
    )
    op.create_index(op.f('ix_agent_threat_intel_versions_tenant_id'), 'agent_threat_intel_versions', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('client_message_id', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('mitre_technique_id', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.Enum('Low', 'Medium', 'High', 'Critical', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('New', 'Investigating', 'Resolved', 'FalsePositive', 'Suppressed', name='alertstatus'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('raw_payload_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_alerts_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alerts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'client_message_id', name='uq_alert_idempotency')
    )
    op.create_index('ix_alert_tenant_severity_status_detected', 'alerts', ['tenant_id', 'severity', 'status', 'detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('audit_logs_grid',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('payload_json', sqlite.JSON(), nullable=True),
    sa.Column('ed25519_signature', sa.LargeBinary(), nullable=False),
    sa.Column('signing_key_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_audit_logs_grid_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_grid_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs_grid')),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'sequence_number', name='uq_audit_log_sequence')
    )
    op.create_index(op.f('ix_audit_logs_grid_tenant_id'), 'audit_logs_grid', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_agent_sequence', 'audit_logs_grid', ['tenant_id', 'agent_id', 'sequence_number'], unique=False)
    op.create_table('command_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('parameters_json', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Dispatched', 'Acknowledged', 'Completed', 'Failed', name='commandstatus'), nullable=False),
    sa.Column('issued_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_command_queue_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_command_queue_issued_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_command_queue_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_queue'))
    )
    op.create_index(op.f('ix_command_queue_tenant_id'), 'command_queue', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sessions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_user_roles_granted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('alert_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('artifact_metadata_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_artifacts_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_artifacts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_artifacts'))
    )
    op.create_index(op.f('ix_alert_artifacts_tenant_id'), 'alert_artifacts', ['tenant_id'], unique=False)
    op.create_table('alert_correlations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('primary_alert_id', sa.String(length=36), nullable=False),
    sa.Column('related_alert_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_alert_id'], ['alerts.id'], name=op.f('fk_alert_correlations_primary_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_alert_id'], ['alerts.id'], name=op.f('fk_alert_correlations_related_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_correlations_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_correlations'))
    )
    op.create_index(op.f('ix_alert_correlations_tenant_id'), 'alert_correlations', ['tenant_id'], unique=False)
    op.create_table('alert_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_details_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_details_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_details'))
    )
    op.create_index(op.f('ix_alert_details_tenant_id'), 'alert_details', ['tenant_id'], unique=False)
    op.create_table('alert_status_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.Enum('New', 'Investigating', 'Resolved', 'FalsePositive', 'Suppressed', name='alertstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('New', 'Investigating', 'Resolved', 'FalsePositive', 'Suppressed', name='alertstatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_status_changes_alert_id_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_alert_status_changes_changed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_status_changes_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_status_changes'))
    )
    op.create_index(op.f('ix_alert_status_changes_tenant_id'), 'alert_status_changes', ['tenant_id'], unique=False)
    op.create_table('command_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('response_payload_json', sqlite.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['command_queue.id'], name=op.f('fk_command_responses_command_id_command_queue'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_command_responses_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_responses'))
    )
    op.create_index(op.f('ix_command_responses_tenant_id'), 'command_responses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_responses_tenant_id'), table_name='command_responses')
    op.drop_table('command_responses')
    op.drop_index(op.f('ix_alert_status_changes_tenant_id'), table_name='alert_status_changes')
    op.drop_table('alert_status_changes')
    op.drop_index(op.f('ix_alert_details_tenant_id'), table_name='alert_details')
    op.drop_table('alert_details')
    op.drop_index(op.f('ix_alert_correlations_tenant_id'), table_name='alert_correlations')
    op.drop_table('alert_correlations')
    op.drop_index(op.f('ix_alert_artifacts_tenant_id'), table_name='alert_artifacts')
    op.drop_table('alert_artifacts')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_command_queue_tenant_id'), table_name='command_queue')
    op.drop_table('command_queue')
    op.drop_index('ix_audit_tenant_agent_sequence', table_name='audit_logs_grid')
    op.drop_index(op.f('ix_audit_logs_grid_tenant_id'), table_name='audit_logs_grid')
    op.drop_table('audit_logs_grid')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index('ix_alert_tenant_severity_status_detected', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agent_threat_intel_versions_tenant_id'), table_name='agent_threat_intel_versions')
    op.drop_table('agent_threat_intel_versions')
    op.drop_index(op.f('ix_agent_heartbeats_tenant_id'), table_name='agent_heartbeats')
    op.drop_table('agent_heartbeats')
    op.drop_index(op.f('ix_agent_configurations_tenant_id'), table_name='agent_configurations')
    op.drop_table('agent_configurations')
    op.drop_table('agent_certificates')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('threat_intel_packages')
    op.drop_index(op.f('ix_system_logs_tenant_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('threat_intel_versions')
    op.drop_table('tenants')
    op.drop_table('roles')
    # ### end Alembic commands ###
